export const GET_EXPERIENCES_REQUEST = "EXPERIENCE.GET_EXPERIENCES_REQUEST";
export const GET_EXPERIENCES_SUCCESS = "EXPERIENCE.GET_EXPERIENCES_SUCCESS";
export const GET_EXPERIENCES_FAILURE = "EXPERIENCE.GET_EXPERIENCES_FAILURE";

export const GET_DETAIL_REQUEST = "EXPERIENCE.GET_DETAIL_REQUEST";
export const GET_DETAIL_SUCCESS = "EXPERIENCE.GET_DETAIL_SUCCESS";
export const GET_DETAIL_FAILURE = "EXPERIENCE.GET_DETAIL_FAILURE";

export const CREATE_EXPERIENCE_REQUEST = "EXPERIENCE.CREATE_EXPERIENCE_REQUEST";
export const CREATE_EXPERIENCE_SUCCESS = "EXPERIENCE.CREATE_EXPERIENCE_SUCCESS";
export const CREATE_EXPERIENCE_FAILURE = "EXPERIENCE.CREATE_EXPERIENCE_FAILURE";

export const EDIT_EXPERIENCE_REQUEST = "EXPERIENCE.EDIT_EXPERIENCE_REQUEST";
export const EDIT_EXPERIENCE_SUCCESS = "EXPERIENCE.EDIT_EXPERIENCE_SUCCESS";
export const EDIT_EXPERIENCE_FAILURE = "EXPERIENCE.EDIT_EXPERIENCE_FAILURE";
